export const cacheKeys = {
  profile: "profile",
  myResumeList: "my-resume-list",
  resumeContent: "resume-content",
  resumeComparison: "resume-comparison",
  jobPostings: "job-postings",
  jobView: "job-view",
  myJobPostings: "my-job-postings",
  companyJobPostings: "company-job-postings",
  myJobApplications: "my-job-applications",
  appliedJobDetails: "applied-job-details",
  jobApplication: "job-application",
  jobApplicationStatus: "job-application-status",
  jobApplicants: "job-applicants",
  jobOwnership: "job-ownership",
  jobMatching: "job-matching",
  rankApplicants: "rank-applicants",
  jobsWithApplicants: "jobs-with-applicants",
  professions: "professions",
  jobSeekerAnalytics: "job-seeker-analytics",
  companyAnalytics: "company-analytics",
  adminAnalytics: "admin-analytics",
};
