export const pages = {
  login: "/",
  register: "/register",
  jobPortal: "/job-portal",
  jobSeekerRegister: "/register/job-seeker",
  companyRegister: "/register/company",
  manageJobs: "/manage-jobs",
  manageUsers: "/manage-users",
  myJobPostings: "/my-job-postings",
  viewApplicants: "/view-applicants",
  myApplications: "/my-applications",
  myResume: "/my-resume",
  resumeOptimizer: "/resume-optimizer",
  jobMatcher: "/job-matcher",
  editProfile: "/edit-profile",
  viewProfile: "/view-profile",
  createJob: "/create-job",
  editJob: (id: string) => `/edit-job/${id}`,
  viewJob: (id: string) => `/jobs/${id}`,
  redirect: "/redirect",
  applyForJob: (jobId: string) => `/apply-for-job/${jobId}`,
};

export const api = {
  jobSeekerRegister: "/api/register/job-seeker",
  companyRegister: "/api/register/company",
  adminRegister: "/api/register/admin",
  profile: "/api/profile",
  editProfile: "/api/profile/edit-profile",
  jobSeekerResume: "/api/job-seeker/upload-resume",
  extractResumeText: "/api/utils/extract-resume-text",
  chatWithResume: "/api/chat/with-resume",
  compareResume: "/api/compare-resume",
  s3: "/api/s3",
  processResume: "/api/process-resume",
  createJob: "/api/jobs/create",
  getMyJobPostings: "/api/jobs/by-user",
  updateJob: (id: string) => `/api/jobs/update/${id}`,
  viewJob: (id: string) => `/api/jobs/${id}/view`,
  processJobPosting: "/api/process-job-posting",
  deleteJob: (id: string) => `/api/jobs/delete/${id}`,
  listJobs: "/api/jobs/list",
  listJobsByCompany: "/api/jobs/list-by-company",
  generateCoverLetter: "/api/generate-cover-letter",
};
