export const pages = {
  login: "/",
  register: "/register",
  jobPortal: "/job-portal",
  jobSeekerRegister: "/register/job-seeker",
  companyRegister: "/register/company",
  manageJobs: "/manage-jobs",
  manageUsers: "/manage-users",
  myJobPostings: "/my-job-postings",
  myApplications: "/my-applications",
  myResume: "/my-resume",
  resumeOptimizer: "/resume-optimizer",
  jobMatcher: "/job-matcher",
  editProfile: "/edit-profile",
  viewProfile: "/view-profile",
  createJob: "/create-job",
  editJob: (id: string) => `/edit-job/${id}`,
  viewJob: (id: string) => `/jobs/${id}`,
  applyForJob: (jobId: string) => `/apply-for-job/${jobId}`,
  viewMyApplication: (id: string) => `/my-applications/view/${id}`,
  viewApplicants: (jobId: string, jobTitle: string) =>
    `/view-applicants/${jobId}/${encodeURIComponent(jobTitle)}`,
  rankApplicants: "/rank-applicants",
  viewApplication: (id: string) => `/view-application/${id}`,
  dashboard: "/dashboard",
};

export const api = {
  jobSeekerRegister: "/api/register/job-seeker",
  companyRegister: "/api/register/company",
  adminRegister: "/api/register/admin",
  profile: "/api/profile",
  editProfile: "/api/profile/edit-profile",
  jobSeekerResume: "/api/job-seeker/upload-resume",
  extractResumeText: "/api/utils/extract-resume-text",
  chatWithResume: "/api/chat/with-resume",
  chatWithApplication: "/api/chat/with-application",
  interviewPractice: "/api/chat/interview-practice",
  compareResume: "/api/compare-resume",
  s3: "/api/s3",
  processResume: "/api/process-resume",
  createJob: "/api/jobs/create",
  getMyJobPostings: "/api/jobs/by-user",
  updateJob: (id: string) => `/api/jobs/update/${id}`,
  viewJob: (id: string) => `/api/jobs/${id}/view`,
  viewJobWithoutInc: (id: string) => `/api/jobs/${id}/view-without-inc`,
  processJobPosting: "/api/process-job-posting",
  deleteJob: (id: string) => `/api/jobs/delete/${id}`,
  listJobs: "/api/jobs/list",
  listJobsByCompany: "/api/jobs/list-by-company",
  generateCoverLetter: "/api/generate-cover-letter",
  createJobApplication: "/api/job-application/create",
  getMyJobApplications: "/api/job-application/read/mine",
  readJobApplication: (id: string) => `/api/job-application/read/${id}`,
  deleteJobApplication: (id: string) => `/api/job-application/delete/${id}`,
  hasAppliedForJob: (jobId: string) =>
    `/api/job-application/read/has-applied/${jobId}`,
  getJobApplicants: (jobId: string) =>
    `/api/job-applicants/view-by-job-id/${jobId}`,
  checkJobOwnership: "/api/job-applicants/check-authorized",
  updateJobApplication: (id: string) => `/api/job-application/update/${id}`,
  jobMatching: "/api/job-matching",
  rankApplicants: "/api/rank-applicants",
  jobsWithApplicants: "/api/company/jobs-with-applicants",
  professions: "/api/professions",
  jobSeekerAnalytics: "/api/dashboard/job-seeker-analytics",
  companyAnalytics: "/api/dashboard/company-analytics",
  adminAnalytics: "/api/dashboard/admin-analytics",
};
